### ISSUE TITLE
let: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by Jean-MichelC** [tashrifsanil/org-easy-img-insert#3]
Hello,

I'm interrested in this function, seen in MELPA.

But so far :
1) copied the auto-img-link-insert.el in an empty scratch
2) M-x eval-buffer
3) in an org-buffer : M-x auto-img-link-insert
4) at prompt : given this link "https://guides.github.com/activities/hello-world/create-new-repo.png" RET
5) then : test-name RET test-caption-RET
6) I get a "let: Wrong type argument: stringp, nil" and nothing happens in my org-buffer

Btw, I have ideas for extending the fonctionnalities, if you are interrested. My coding is too weak ...

**Comment by my7h3le** [comment]
Hi,

Thanks for checking out the package. Hmm, are you on emacs 24.4 or greater, and also are you running Windows, Linux, or Mac? If you are on Windows, does the `wget` command work? I ask because on my end I don't have this issue. 

And I would be interested in your ideas to extend functionalities. Hopefully I can implement them.

Some screenshots:
![screenshot from 2016-09-11 11-04-07](https://cloud.githubusercontent.com/assets/7899547/18418237/7c3de040-7810-11e6-91e6-39131bb266c8.png)
![screenshot from 2016-09-11 11-04-35](https://cloud.githubusercontent.com/assets/7899547/18418240/89816416-7810-11e6-9f59-b9bab8286d38.png)
![screenshot from 2016-09-11 11-10-58](https://cloud.githubusercontent.com/assets/7899547/18418247/a33b5baa-7810-11e6-84e1-73b59cc0d8e6.png)
![screenshot from 2016-09-11 11-11-03](https://cloud.githubusercontent.com/assets/7899547/18418246/a33a7d66-7810-11e6-8e7c-bcc94d236913.png)
![screenshot from 2016-09-11 11-11-05](https://cloud.githubusercontent.com/assets/7899547/18418245/a339c4d4-7810-11e6-8db0-5fb7904a6050.png)
