### ISSUE TITLE
org-download?

### ISSUE THREAD

**Issue by alphapapa** [tashrifsanil/org-easy-img-insert#7]
Hi again,

I almost hate to point this out, seeing as how you've been working more on this package, and even just renamed it... but I just came across this package that I had forgotten about:

https://github.com/abo-abo/org-download

It seems like it does the same things, with a few more features and options.  You should probably check it out.  :)

**Comment by my7h3le** [comment]
The funny thing is that I actually checked out that same package before I started working on this one. When I tried it out I could view it in the buffer, but it didn't seem to embed itself into the org file. I'm pretty sure I wasn't using the package incorrectly, so instead of trying to get to grips with it, I just created this as a side project. I wasn't expecting anyone to actually use this, it was more for personal use I guess

**Comment by alphapapa** [comment]
Hm, well I admit I haven't used it myself yet, but its readme says, "Point B (the target) is an Emacs org-mode buffer where the inline link will be inserted. Several customization options will determine where exactly on the file system the file will be stored."  So it sounds like that's what it's supposed to do.
